In [ ]:
# Libraries to help with reading and manipulating data
import numpy as np
import pandas as pd

# Libraries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
import io

try:
    uploaded
except NameError:
    uploaded = files.upload()

Saving GlobalFindexDatabase2025.csv to GlobalFindexDatabase2025.csv

In [ ]:
# loading the dataset
data = pd.read_csv("GlobalFindexDatabase2025.csv")

In [ ]:
df = data.copy()

In [ ]:
df.head()

,year,economy,economycode,regionwb,pop_adult,wpid_random,wgt,female,age,educ,...,fin48e,fin48f,fin49a,fin49b,fin49c,fin49d,fin49e,fin49f,fin50,fin51
0,2024,Nicaragua,NIC,Latin America & Caribbean (excluding high income),4830854,111111345,0.927315,1,53,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,Costa Rica,CRI,Latin America & Caribbean (excluding high income),4118576,111111579,1.383884,2,48,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,Mali,MLI,Sub-Saharan Africa (excluding high income),12725942,111112511,1.323486,1,40,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,Kuwait,KWT,High income,3950546,111113432,1.475693,1,25,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
4,2024,Turkiye,TUR,Europe & Central Asia (excluding high income),66691005,111115194,0.651801,2,72,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0

In [ ]:
df.describe()

,year,pop_adult,wpid_random,wgt,female,age,educ,inc_q,emp_in,urbanicity,...,fin48e,fin48f,fin49a,fin49b,fin49c,fin49d,fin49e,fin49f,fin50,fin51
count,144090.0,1.440900e+05,1.440900e+05,144090.000000,144090.000000,144090.000000,143502.000000,143070.000000,140070.000000,141564.000000,...,8037.000000,8037.000000,8037.000000,8037.000000,8037.000000,8036.000000,8037.000000,8037.000000,67913.000000,33264.000000
mean,2024.0,7.978480e+07,1.611178e+08,1.000000,1.475467,43.071872,1.944823,3.195149,1.401264,1.438176,...,1.666667,1.839243,1.749907,1.702625,1.604330,1.673718,1.700759,1.795322,1.537879,1.262296
std,0.0,2.423602e+08,2.885293e+07,0.745893,0.499399,18.081725,0.690607,1.418575,0.490156,0.496165,...,0.522276,0.432085,0.490491,0.513539,0.528172,0.525218,0.506961,0.447645,0.556804,0.463387
min,2024.0,3.001380e+05,1.111113e+08,0.078167,1.000000,15.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2024.0,4.231057e+06,1.361806e+08,0.478136,1.000000,28.000000,1.000000,2.000000,1.000000,1.000000,...,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000
50%,2024.0,9.588258e+06,1.611931e+08,0.794205,1.000000,40.000000,2.000000,3.000000,1.000000,1.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000
75%,2024.0,3.396098e+07,1.860201e+08,1.284907,2.000000,57.000000,2.000000,4.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,2024.0,1.176679e+09,2.111111e+08,7.549079,2.000000,100.000000,3.000000,5.000000,2.000000,2.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [ ]:
df.shape

(144090, 199)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144090 entries, 0 to 144089
Columns: 199 entries, year to fin51
dtypes: float64(185), int64(11), object(3)
memory usage: 218.8+ MB

In [ ]:
columns = [
    'educ', 'economycode', 'pop_adult', 'wgt', 'female', 'age', 'inc_q', 'emp_in',
    'urbanicity', 'account', 'borrowed', 'saved', 'receive_wages',
    'receive_transfers', 'receive_pensions', 'pay_utilities', 'fin19',
    'fin22a', 'fin24a', 'fin24c', 'fh2a', 'fh1', 'fh2',
    'fin37', 'fin38', 'fin42', 'internet_use', 'con1'
]

df_subset = df[columns]

In [ ]:
df_subset.head()

,educ,economycode,pop_adult,wgt,female,age,inc_q,emp_in,urbanicity,account,...,fin24a,fin24c,fh2a,fh1,fh2,fin37,fin38,fin42,internet_use,con1
0,1.0,NIC,4830854,0.927315,1,53,5.0,1.0,1.0,0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,1
1,2.0,CRI,4118576,1.383884,2,48,3.0,1.0,1.0,1,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,1
2,1.0,MLI,12725942,1.323486,1,40,2.0,1.0,1.0,0,...,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1,1
3,3.0,KWT,3950546,1.475693,1,25,5.0,1.0,2.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
4,2.0,TUR,66691005,0.651801,2,72,4.0,2.0,2.0,1,...,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,0,1

In [ ]:
df_subset.shape

(144090, 28)

In [ ]:
from google.colab import files
import io

uploaded = files.upload()

Saving CountryIncomeGroup.xlsx to CountryIncomeGroup.xlsx

In [ ]:
# loading the dataset
incomedata = pd.read_excel("CountryIncomeGroup.xlsx")

In [ ]:
incomedata.head()

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN

In [ ]:
incomedata_renamed = incomedata.rename(columns={'Code': 'economycode'})

df_subset = pd.merge(df_subset, incomedata_renamed[['economycode', 'Income group']], on='economycode', how='left')

display(df_subset.head())

,educ,economycode,pop_adult,wgt,female,age,inc_q,emp_in,urbanicity,account,...,fin24c,fh2a,fh1,fh2,fin37,fin38,fin42,internet_use,con1,Income group
0,1.0,NIC,4830854,0.927315,1,53,5.0,1.0,1.0,0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,1,Lower middle income
1,2.0,CRI,4118576,1.383884,2,48,3.0,1.0,1.0,1,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,1,High income
2,1.0,MLI,12725942,1.323486,1,40,2.0,1.0,1.0,0,...,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1,1,Low income
3,3.0,KWT,3950546,1.475693,1,25,5.0,1.0,2.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,High income
4,2.0,TUR,66691005,0.651801,2,72,4.0,2.0,2.0,1,...,2.0,2.0,2.0,2.0,2.0,1.0,2.0,0,1,Upper middle income

In [ ]:
unique_income_groups = df_subset['Income group'].unique()
display(unique_income_groups)

array(['Lower middle income', 'High income', 'Low income',
       'Upper middle income'], dtype=object)

In [ ]:
df_subset = df_subset[df_subset['Income group'] != 'High income']
display(df_subset.head())

,educ,economycode,pop_adult,wgt,female,age,inc_q,emp_in,urbanicity,account,...,fin24c,fh2a,fh1,fh2,fin37,fin38,fin42,internet_use,con1,Income group
0,1.0,NIC,4830854,0.927315,1,53,5.0,1.0,1.0,0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,1,Lower middle income
2,1.0,MLI,12725942,1.323486,1,40,2.0,1.0,1.0,0,...,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1,1,Low income
4,2.0,TUR,66691005,0.651801,2,72,4.0,2.0,2.0,1,...,2.0,2.0,2.0,2.0,2.0,1.0,2.0,0,1,Upper middle income
6,1.0,HND,7345357,0.434152,1,57,3.0,1.0,1.0,0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1,2,Lower middle income
9,2.0,MDA,1966418,0.590505,1,52,3.0,2.0,1.0,0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0,2,Upper middle income

In [ ]:
economy_counts = df_subset['Income group'].value_counts()
display(economy_counts)

Income group
Upper middle income    43668
Lower middle income    38231
Low income             13021
Name: count, dtype: int64

In [ ]:
df_subset.to_csv('combined_dataset_weight.csv', index=False)
print('combined_dataset_weight.csv has been successfully created.')

combined_dataset_weight.csv has been successfully created.

In [ ]:
from google.colab import files

files.download('combined_dataset_weight.csv')